import { IGridColumn } from '~/components/UI';
import { ENUM_DECIMAL, ENUM_WIDTH } from '~/enums';

export default [
  {
    header: '파일첨부',
    name: 'files',
    width: ENUM_WIDTH.M,
    format: 'file',
    options: {
      file_mgmt_type_cd: 'FIL_STD_PROD',
      ok_type: 'json',
      reference_col: 'prod_uuid',
    },
  },
  {
    header: '품목UUID',
    name: 'prod_uuid',
    alias: 'uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    hidden: true,
  },
  {
    header: '품번',
    name: 'prod_no',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    requiredField: true,
  },
  {
    header: '구품번',
    name: 'prod_no_pre',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    requiredField: false,
  },
  {
    header: '품목명',
    name: 'prod_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    requiredField: true,
  },
  {
    header: '품목유형UUID',
    name: 'item_type_uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    requiredField: true,
    hidden: true,
  },
  {
    header: '품목유형명',
    name: 'item_type_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
    requiredField: true,
  },
  {
    header: '제품유형UUID',
    name: 'prod_type_uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    hidden: true,
  },
  {
    header: '제품유형명',
    name: 'prod_type_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
  },
  {
    header: '모델UUID',
    name: 'model_uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    hidden: true,
  },
  {
    header: '모델명',
    name: 'model_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
  },
  {
    header: '리비전',
    name: 'rev',
    width: ENUM_WIDTH.S,
    filter: 'text',
    editable: true,
    requiredField: true,
  },
  {
    header: '규격',
    name: 'prod_std',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
  },
  {
    header: '단위UUID',
    name: 'unit_uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    requiredField: true,
    hidden: true,
  },
  {
    header: '단위명',
    name: 'unit_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
    requiredField: true,
  },
  {
    header: 'LOT 사용여부',
    name: 'lot_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '사용여부',
    name: 'use_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '품목활성상태',
    name: 'active_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: 'BOM유형uuid',
    name: 'bom_type_uuid',
    width: ENUM_WIDTH.M,
    filter: 'text',
    editable: true,
    format: 'popup',
    hidden: true,
  },
  {
    header: 'BOM유형코드',
    name: 'bom_type_cd',
    width: ENUM_WIDTH.M,
    filter: 'text',
    editable: true,
    format: 'popup',
    hidden: true,
  },
  {
    header: 'BOM유형명',
    name: 'bom_type_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
  },
  {
    header: '구매주문가능여부',
    name: 'mat_order_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '발주최소수량',
    name: 'mat_order_min_qty',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STOCK,
  },
  {
    header: '발주소요일',
    name: 'mat_supply_days',
    width: ENUM_WIDTH.S,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NORMAL,
  },
  {
    header: '재고관리여부',
    name: 'inv_use_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '포장단위수량',
    name: 'inv_package_qty',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STOCK,
  },
  {
    header: '안전재고수량',
    name: 'inv_safe_qty',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STOCK,
  },
  {
    header: '입고창고UUID',
    name: 'inv_to_store_uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    hidden: true,
  },
  {
    header: '입고창고',
    name: 'inv_to_store_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
  },
  {
    header: '입고위치UUID',
    name: 'inv_to_location_uuid',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    hidden: true,
  },
  {
    header: '입고위치',
    name: 'inv_to_location_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
  },
  {
    header: '고객주문가능여부',
    name: 'sal_order_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '수입검사여부',
    name: 'qms_receive_insp_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '공정검사여부',
    name: 'qms_proc_insp_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '최종검사여부',
    name: 'qms_final_insp_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '계획유형UUID',
    name: 'prd_plan_type_uuid',
    width: ENUM_WIDTH.M,
    filter: 'text',
    editable: true,
    hidden: true,
  },
  {
    header: '계획유형코드',
    name: 'prd_plan_type_cd',
    width: ENUM_WIDTH.M,
    filter: 'text',
    editable: true,
    format: 'popup',
    hidden: true,
  },
  {
    header: '계획유형명(MPS/MRP)',
    name: 'prd_plan_type_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    editable: true,
    format: 'popup',
  },
  {
    header: '생산품여부',
    name: 'prd_active_fg',
    width: ENUM_WIDTH.XS,
    editable: true,
    format: 'check',
    requiredField: true,
  },
  {
    header: '생산최소수량',
    name: 'prd_min',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STOCK,
  },
  {
    header: '생산최대수량',
    name: 'prd_max',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STOCK,
  },
  {
    header: '폭',
    name: 'width',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NORMAL,
  },
  {
    header: '길이',
    name: 'length',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NORMAL,
  },
  {
    header: '높이',
    name: 'height',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NORMAL,
  },
  {
    header: '중량',
    name: 'weight',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NORMAL,
  },
  {
    header: '두께',
    name: 'thickness',
    width: ENUM_WIDTH.M,
    editable: true,
    filter: 'number',
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NORMAL,
  },
  {
    header: '재질',
    name: 'material',
    width: ENUM_WIDTH.M,
    filter: 'text',
    editable: true,
  },
  {
    header: '색상',
    name: 'color',
    width: ENUM_WIDTH.M,
    filter: 'text',
    editable: true,
  },
  {
    header: '생산원가',
    name: 'work_price',
    width: ENUM_WIDTH.M,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_PRICE,
    filter: 'text',
    editable: true,
  },
] as IGridColumn[];
