version: 0.2

phases:
  install:
    commands:
      - yarn add parcel-bundler@1.12.5
      - yarn install
  pre_build:
    commands:
  build:
    commands:
      - yarn build
      - echo "success build"
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  base-directory: 'build'