version: 0.2

phases:
  install:
    commands:
      - yarn install
  pre_build:
    commands:
  build:
    commands:
      - yarn build
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  base-directory: 'build'