version: 0.2

phases:
  install:
    commands:
      - yarn add parcel-bundler@1.12.5
      - yarn install
  pre_build:
    commands:
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync ./build s3://najs.isos.kr
      - aws cloudfront create-invalidation --distribution-id E3FEPPSU80W9NC --paths  "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
