import { IGridColumn } from '~/components/UI';
import { ENUM_DECIMAL, ENUM_WIDTH } from '~/enums';

export default <IGridColumn[]>[
  {
    header: '작업지시UUID',
    name: 'order_uuid',
    alias: 'uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '우선순위',
    name: 'priority',
    width: ENUM_WIDTH.M,
    editable: true,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NOMAL,
    filter: 'number',
  },
  {
    header: '지시일',
    name: 'reg_date',
    width: ENUM_WIDTH.M,
    format: 'date',
    filter: 'date',
    requiredField: true,
  },
  {
    header: '지시번호',
    name: 'order_no',
    width: ENUM_WIDTH.M,
    editable: true,
  },
  {
    header: '작업장UUID',
    name: 'workings_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
    requiredField: true,
  },
  {
    header: '작업장',
    name: 'workings_nm',
    width: ENUM_WIDTH.M,
    editable: true,
    format: 'popup',
    filter: 'text',
    requiredField: true,
    noSave: true,
  },
  {
    header: '품목UUID',
    name: 'prod_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
    requiredField: true,
  },
  {
    header: '품번',
    name: 'prod_no',
    width: ENUM_WIDTH.L,
    filter: 'text',
    requiredField: true,
    noSave: true,
  },
  {
    header: '품목',
    name: 'prod_nm',
    width: ENUM_WIDTH.L,
    filter: 'text',
    requiredField: true,
    noSave: true,
  },
  {
    header: '제품유형',
    name: 'prod_type_nm',
    width: ENUM_WIDTH.M,
    filter: 'text',
    noSave: true,
  },
  {
    header: '품목유형',
    name: 'item_type_nm',
    width: ENUM_WIDTH.M,
    filter: 'text',
    noSave: true,
  },
  {
    header: '모델',
    name: 'model_nm',
    width: ENUM_WIDTH.M,
    filter: 'text',
    noSave: true,
  },
  {
    header: 'Rev',
    name: 'rev',
    width: ENUM_WIDTH.M,
    filter: 'text',
    noSave: true,
  },
  {
    header: '규격',
    name: 'prod_std',
    width: ENUM_WIDTH.M,
    filter: 'text',
    noSave: true,
  },
  {
    header: '단위',
    name: 'unit_nm',
    width: ENUM_WIDTH.S,
    filter: 'text',
    noSave: true,
  },
  {
    header: '계획수량',
    name: 'plan_qty',
    width: ENUM_WIDTH.M,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STCOK,
  },
  {
    header: '지시수량',
    name: 'qty',
    width: ENUM_WIDTH.M,
    editable: true,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_STCOK,
    requiredField: true,
  },
  {
    header: '지시순번',
    name: 'seq',
    width: ENUM_WIDTH.S,
    editable: true,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NOMAL,
    hidden: true,
  },
  {
    header: '작업교대UUID',
    name: 'shift_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
    requiredField: true,
  },
  {
    header: '작업교대',
    name: 'shift_nm',
    width: ENUM_WIDTH.M,
    editable: true,
    format: 'combo',
    filter: 'text',
    requiredField: true,
    noSave: true,
  },
  {
    header: '수주상세UUID',
    name: 'sal_order_detail_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '비고',
    name: 'remark',
    width: ENUM_WIDTH.XL,
    editable: true,
    filter: 'text',
  },
];
