const URL_PATH = {
  INV:{
    STORE:{
      GET:{
        /** UUID 문자열 변환 필요 */
        STORE:'/inv/store/{uuid}',
        STORES:'/inv/stores',
        TOTAL_HISTORY:'/inv/stores/total-history',
        INDIVIDUAL_HISTORY:'/inv/stores/individual-history',
        TYPE_HISTORY:'/inv/stores/type-history',
        HISTORY_BY_TRANSACTION:'/inv/stores/history-by-transaction',
        STOCKS_RETURN:'/inv/stores/stocks/return',
        STOCKS:'/inv/stores/stocks'
      },
      POST:{
        STORES:'/inv/stores' 
      },
      PUT:{
        STORES:'/inv/stores'
      },
      PATCH:{
        STORES:'/inv/stores'
      },
      DELETE:{
        STORES:'/inv/stores'
      },
    },
    STOCK_REJECT:{
      GET:{
        /** UUID 문자열 변환 필요 */
        STOCK_REJECT:'/inv/stock-reject/{uuid}',
        STOCK_REJECTS:'/inv/stock-rejects'
      },
      POST:{
        STOCK_REJECTS:'/inv/stock-rejects'
      },
      PUT:{
        STOCK_REJECTS:'/inv/stock-rejects'
      },
      PATCH:{
        STOCK_REJECTS:'/inv/stock-rejects'
      },
      DELETE:{
        STOCK_REJECTS:'/inv/stock-rejects'
      }
    },
    MOVE:{
      GET:{
        /** UUID 문자열 변환 필요 */
        MOVE:'/inv/move/{uuid}',
        MOVES:'/inv/moves'
      },
      POST:{
        MOVES:'/inv/moves'
      },
      PUT:{
        MOVES:'/inv/moves'
      },
      PATCH:{
        MOVES:'/inv/moves'
      },
      DELETE:{
        MOVES:'/inv/moves'
      }
    }
  },
  MAT:{
    RELEASE:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RELEASE:'/mat/release/{uuid}',
        RELEASES:'/mat/releases',
        REPORT:'/mat/releases/report'
      },
      POST:{
        RELEASES:'/mat/releases',
      },
      PUT:{
        RELEASES:'/mat/releases',
      },
      PATCH:{
        RELEASES:'/mat/releases',
      },
      DELETE:{
        RELEASES:'/mat/releases',
      }
    },
    RETURN:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RETURN:'/mat/return/{uuid}',
        RETURNS:'/mat/returns',
        REPORT:'/mat/returns/report',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/mat/return/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/mat/return/{uuid}/include-details',
      },
      POST:{
        RETURNS:'/mat/returns',
      },
      PUT:{
        RETURNS:'/mat/returns',
      },
      PATCH:{
        RETURNS:'/mat/returns',
      },
      DELETE:{
        RETURNS:'/mat/returns',
      }
    },
    RETURN_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RETURN_DETAIL:'/mat/return-detail/{uuid}',
        RETURN_DETAILS:'/mat/return-details',
      }
    },
    ORDER:{
      GET:{
        REPORT:'/mat/orders/report',
        /** UUID 문자열 변환 필요 */
        ORDER:'/mat/order/{uuid}',
        ORDERS:'/mat/orders',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/mat/order/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/mat/order/{uuid}/include-details',
      },
      POST:{
        ORDERS:'/mat/orders',
      },
      PUT:{
        ORDERS:'/mat/orders',
      },
      PATCH:{
        ORDERS:'/mat/orders',
      },
      DELETE:{
        ORDERS:'/mat/orders',
      }
    },
    ORDER_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        ORDER_DETAIL:'/mat/order-detail/{uuid}',
        ORDER_DETAILS:'/mat/order-details',
      },
      PUT:{
        COMPLETE:'/mat/order-details/complete'
      }
    },
    RECEIVE:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RECEIVE:'/mat/receive/{uuid}',
        RECEIVES:'/mat/receives',
        LOT_TRACKING:'/mat/receives/lot-tracking',
        REPORT:'/mat/receives/report',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/mat/receive/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/mat/receive/{uuid}/include-details',
      },
      POST:{
        RECEIVES:'/mat/receives',
      },
      PUT:{
        RECEIVES:'/mat/receives',
      },
      PATCH:{
        RECEIVES:'/mat/receives',
      },
      DELETE:{
        RECEIVES:'/mat/receives',
      }
    },
    RECEIVE_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RECEIVE_DETAIL:'/mat/receive-detail/{uuid}',
        RECEIVE_DETAILS:'/mat/receive-details',
      }
    }
  },
  OUT:{
    RECEIVE:{
      GET:{
        REPORT:'/out/receives/report',
        /** UUID 문자열 변환 필요 */
        RECEIVE:'/out/receive/{uuid}',
        RECEIVES:'/out/receives',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/out/receive/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/out/receive/{uuid}/include-details',
      },
      POST:{
        RECEIVES:'/out/receives',
      },
      PUT:{
        RECEIVES:'/out/receives',
      },
      PATCH:{
        RECEIVES:'/out/receives',
      },
      DELETE:{
        RECEIVES:'/out/receives',
      }
    },
    RECEIVE_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RECEIVE_DETAIL:'/out/receive-detail/{uuid}',
        RECEIVE_DETAILS:'/out/receive-details',
      }
    },
    RELEASE:{
      REPORT:'/out/releases/report',
      /** UUID 문자열 변환 필요 */
      RELEASE:'/out/release/{uuid}',
      RELEASES:'/out/releases',
      /** UUID 문자열 변환 필요 */
      DETAILS:'/out/release/{uuid}/details',
      /** UUID 문자열 변환 필요 */
      INCLUDE_DETAILS:'/out/release/{uuid}/include-details',
    },
    RELEASES_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RELEASES_DETAIL:'/out/release-detail/{uuid}',
        RELEASE_DETAILS:'/out/release-details',
      }
    }
  },
  PRD:{
    WORK:{
      GET:{
        REPORT:'/prd/works/report',
        /** UUID 문자열 변환 필요 */
        WORK:'/prd/work/{uuid}',
        WORKS:'/prd/works',
      },
      POST:{
        WORKS:'/prd/works',
      },
      PUT:{
        CANCEL_COMPLETE:'/prd/works/cancel-complete',
        COMPLETE:'/prd/works/complete',
        WORKS:'/prd/works',
      },
      PATCH:{
        WORKS:'/prd/works',
      },
      DELETE:{
        WORKS:'/prd/works',
      }
    },
    WORK_REJECT:{
      GET:{
        REPORT:'/prd/work-rejects/report',
        /** UUID 문자열 변환 필요 */
        REJECT:'/prd/work-reject/{uuid}',
        REJECTS:'/prd/work-rejects',
      },
      POST:{
        REJECTS:'/prd/work-rejects',
      },
      PUT:{
        REJECTS:'/prd/work-rejects',
      },
      PATCH:{
        REJECTS:'/prd/work-rejects',
      },
      DELETE:{
        REJECTS:'/prd/work-rejects',
      }
    },
    WORK_DOWNTIME:{
      GET:{
        REPORT:'/prd/work-downtimes/report',
        /** UUID 문자열 변환 필요 */
        DOWNTIME:'/prd/work-downtime/{uuid}',
        DOWNTIMES:'/prd/work-downtimes',
      },
      POST:{
        DOWNTIMES:'/prd/work-downtimes',
      },
      PUT:{
        DOWNTIMES:'/prd/work-downtimes',
      },
      PATCH:{
        DOWNTIMES:'/prd/work-downtimes',
      },
      DELETE:{
        
      }
    },
    INPUT:{
      GET:{
        ONGOING:'/prd/work-inputs/ongoing',
        ONGOING_GROUP:'/prd/work-inputs/ongoing-group',
        /** UUID 문자열 변환 필요 */
        INPUT:'/prd/work-input/{uuid}',
        INPUTS:'/prd/work-inputs',
      },
      POST:{
        INPUTS:'/prd/work-inputs',
      },
      PUT:{
        INPUTS:'/prd/work-inputs',
      },
      PATCH:{
        INPUTS:'/prd/work-inputs',
      },
      DELETE:{
        INPUTS:'/prd/work-inputs',
        INPUTS_BY_WORK:'/prd/work-inputs/by-work',
      }
    },
    WORKER:{
      GET:{
        /** UUID 문자열 변환 필요 */
        WORKER:'/prd/work-worker/{uuid}',
        WORKERS:'/prd/work-workers',
      },
      POST:{
        WORKERS:'/prd/work-workers',
      },
      PUT:{
        WORKERS:'/prd/work-workers',
      },
      PATCH:{
        WORKERS:'/prd/work-workers',
      },
      DELETE:{
        WORKERS:'/prd/work-workers',
      }
    },
    ROUTING:{
      GET:{
        /** UUID 문자열 변환 필요 */
        ROUTING:'/prd/work-routing/{uuid}',
        ROUTINGS:'/prd/work-routings',
      },
      PUT:{
        ROUTINGS:'/prd/work-routings',
      },
      PATCH:{
        ROUTINGS:'/prd/work-routings',
      }
    },
    RETURN:{
      GET:{
        REPORT:'/prd/returns/report',
        /** UUID 문자열 변환 필요 */
        RETURN:'/prd/return/{uuid}',
        RETURNS:'/prd/returns',
      },
      POST:{
        RETURNS:'/prd/returns',
      },
      PUT:{
        RETURNS:'/prd/returns',
      },
      PATCH:{
        RETURNS:'/prd/returns',
      },
      DELETE:{
        RETURNS:'/prd/returns',
      }
    },
    DEMANDS:{
      GET:{
        /** UUID 문자열 변환 필요 */
        DEMAND:'/prd/demand/{uuid}',
        DEMANDS:'/prd/demands',
      },
      POST:{
        DEMANDS:'/prd/demands',
      },
      PUT:{
        COMPLETE:'/prd/demands/complete',
        DEMANDS:'/prd/demands',
      },
      PATCH:{
        DEMANDS:'/prd/demands',
      },
      DELETE:{
        DEMANDS:'/prd/demands',
      }
    },
    ORDER:{
      GET:{
        /** UUID 문자열 변환 필요 */
        ORDER:'/prd/order/{uuid}',
        ORDERS:'/prd/orders',
      },
      POST:{
        ORDERS:'/prd/orders',
      },
      PUT:{
        COMPLETE:'/prd/orders/complete',
        WORKER_GROUP:'/prd/orders/worker-group',
        ORDERS:'/prd/orders',
      },
      PATCH:{
        ORDERS:'/prd/orders',
      },
      DELETE:{
        ORDERS:'/prd/orders',
      }
    },
    ORDER_ROUTING:{
      GET:{
        /** UUID 문자열 변환 필요 */
        ORDER_ROUTING:'/prd/order-routing/{uuid}',
        ORDER_ROUTINGS:'/prd/order-routings',
      },
      PUT:{
        ORDER_ROUTINGS:'/prd/order-routings',
      },
      PATCH:{
        ORDER_ROUTINGS:'/prd/order-routings',
      },
    },
    ORDER_INPUT:{
      GET:{
        /** UUID 문자열 변환 필요 */
        ROUTING:'/prd/order-routing/{uuid}',
      },
      POST:{
        ROUTINGS:'/prd/order-routings',
      },
      PUT:{
        ROUTINGS:'/prd/order-routings',
      },
      PATCH:{
        ROUTINGS:'/prd/order-routings',
      },
      DELETE:{
        ROUTINGS:'/prd/order-routings',
      }
    },
    ORDER_WORKER:{
      GET:{
        /** UUID 문자열 변환 필요 */
        WORKER:'/prd/order-worker/{uuid}',
        WORKERS:'/prd/order-workers',
      },
      POST:{
        WORKERS:'/prd/order-workers',
      },
      PUT:{
        WORKERS:'/prd/order-workers',
      },
      PATCH:{
        WORKERS:'/prd/order-workers',
      },
      DELETE:{
        WORKERS:'/prd/order-workers',
      }
    },
  },
  SAL:{
    RETURN:{
      GET:{
        REPORT:'/sal/returns/report',
        /** UUID 문자열 변환 필요 */
        RETURN:'/sal/return/{uuid}',
        RETURNS:'/sal/returns',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/sal/return/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/sal/return/{uuid}/include-details',
      },
      POST:{
        RETRUNS:'/sal/returns',
      },
      PUT:{
        RETRUNS:'/sal/returns',
      },
      PATCH:{
        RETRUNS:'/sal/returns',
      },
      DELETE:{
        RETRUNS:'/sal/returns',
      }
    },
    RETURN_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        RETURN_DETAIL:'/sal/return-detail/{uuid}',
        RETURN_DETAILS:'/sal/return-details',
      }
    },
    ORDER:{
      GET:{
        REPORT:'/sal/orders/report',
        /** UUID 문자열 변환 필요 */
        ORDER:'/sal/order/{uuid}',
        ORDERS:'/sal/orders',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/sal/order/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/sal/order/{uuid}/include-details',
      },
      POST:{
        ORDERS:'/sal/orders',
      },
      PUT:{
        ORDERS:'/sal/orders',
      },
      PATCH:{
        ORDERS:'/sal/orders',
      },
      DELETE:{
        ORDERS:'/sal/orders',
      }
    },
    ORDER_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        DETAIL:'/sal/order-detail/{uuid}',
        DETAILS:'/sal/order-details',
      },
      PUT:{
        COMPLETE:'/sal/order-details/complete',
      },
    },
    INCOME:{
      GET:{
        REPORT:'/sal/incomes/report',
        /** UUID 문자열 변환 필요 */
        INCOME:'/sal/income/{uuid}',
        INCOMES:'/sal/incomes',
      },
      POST:{
        INCOMES:'/sal/incomes',
      },
      PUT:{
        INCOMES:'/sal/incomes',
      },
      PATCH:{
        INCOMES:'/sal/incomes',
      },
      DELETE:{
        INCOMES:'/sal/incomes',
      }
    },
    RELEASE:{
      GET:{
        REPORT:'/sal/releases/report',
        /** UUID 문자열 변환 필요 */
        RELEASE:'/sal/release/{uuid}',
        RELEASES:'/sal/releases',
      },
      POST:{
        RELEASES:'/sal/releases',
      },
      PUT:{
        RELEASES:'/sal/releases',
      },
      PATCH:{
        RELEASES:'/sal/releases',
      },
      DELETE:{
        RELEASES:'/sal/releases',
      }
    },
    OUTGO_ORDER:{
      GET:{
        /** UUID 문자열 변환 필요 */
        OUTGO_ORDER:'/sal/outgo-order/{uuid}',
        OUTGO_ORDERS:'/sal/outgo-orders',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/sal/outgo-order/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/sal/outgo-order/{uuid}/include-details',
      },
      POST:{
        OUTGO_ORDERS:'/sal/outgo-orders',
      },
      PUT:{
        OUTGO_ORDERS:'/sal/outgo-orders',
      },
      PATCH:{
        OUTGO_ORDERS:'/sal/outgo-orders',
      },
      DELETE:{
        OUTGO_ORDERS:'/sal/outgo-orders',
      }
    },
    OUTGO_ORDER_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        DETAIL:'/sal/outgo-order-detail/{uuid}',
        DETAILS:'/sal/outgo-order-details',
      },
      PUT:{
        COMPLETE:'/sal/outgo-order-details/complete',
      }
    },
    OUTGO:{
      GET:{
        LOT_TRACKING:'/sal/outgos/lot-tracking',
        REPORT:'/sal/outgos/report',
        /** UUID 문자열 변환 필요 */
        OUTGO:'/sal/outgo/{uuid}',
        OUTGOS:'/sal/outgos',
        /** UUID 문자열 변환 필요 */
        DETAILS:'/sal/outgo/{uuid}/details',
        /** UUID 문자열 변환 필요 */
        INCLUDE_DETAILS:'/sal/outgo/{uuid}/include-details',
      },
      POST:{
        OUTGOS:'/sal/outgos',
      },
      PUT:{
        OUTGOS:'/sal/outgos',
      },
      PATCH:{
        OUTGOS:'/sal/outgos',
      },
      DELETE:{
        OUTGOS:'/sal/outgos',
      }
    },
    OUTGO_DETAIL:{
      GET:{
        /** UUID 문자열 변환 필요 */
        DETAIL:'/sal/outgo-detail/{uuid}',
        DETAILS:'/sal/outgo-details',
      }
    }
  }
}

export const URL_PATH_INV = URL_PATH.INV
export const URL_PATH_MAT = URL_PATH.MAT
export const URL_PATH_OUT = URL_PATH.OUT
export const URL_PATH_PRD = URL_PATH.PRD
export const URL_PATH_SAL = URL_PATH.SAL