import { IGridColumn } from '~/components/UI';
import { ENUM_DECIMAL, ENUM_WIDTH } from '~/enums';

export default [
  {
    header: '세부기준서UUID',
    name: 'insp_detail_uuid',
    alias: 'uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '세부기준서번호',
    name: 'insp_no_sub',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '정기점검',
    name: 'periodicity_fg',
    width: ENUM_WIDTH.M,
    format: 'check',
    editable: true,
    requiredField: true,
  },
  {
    header: '검사기준UUID',
    name: 'insp_item_type_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '검사항목UUID',
    name: 'insp_item_uuid',
    width: ENUM_WIDTH.M,
    filter: 'text',
    hidden: true,
  },
  {
    header: '검사유형',
    name: 'insp_item_type_nm',
    width: ENUM_WIDTH.M,
    filter: 'text',
  },
  {
    header: '검사항목',
    name: 'insp_item_nm',
    width: ENUM_WIDTH.M,
    filter: 'text',
    requiredField: true,
  },
  {
    header: '상세검사내용',
    name: 'insp_item_desc',
    width: ENUM_WIDTH.XL,
    filter: 'text',
  },
  {
    header: '기준',
    name: 'spec_std',
    width: ENUM_WIDTH.M,
    filter: 'text',
    requiredField: true,
  },
  {
    header: 'MIN',
    name: 'spec_min',
    width: ENUM_WIDTH.M,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_INSPECT_SPEC,
    filter: 'number',
  },
  {
    header: 'MAX',
    name: 'spec_max',
    width: ENUM_WIDTH.M,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_INSPECT_SPEC,
    filter: 'number',
  },
  {
    header: '검사방법UUID',
    name: 'insp_method_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '검사방법',
    name: 'insp_method_nm',
    width: ENUM_WIDTH.M,
    format: 'popup',
    filter: 'text',
    editable: true,
  },
  {
    header: '검사구UUID',
    name: 'insp_tool_uuid',
    width: ENUM_WIDTH.M,
    hidden: true,
  },
  {
    header: '검사구',
    name: 'insp_tool_nm',
    width: ENUM_WIDTH.M,
    format: 'popup',
    filter: 'text',
    editable: true,
  },
  {
    header: '주기 기준일',
    name: 'base_date',
    width: ENUM_WIDTH.M,
    format: 'date',
    editable: true,
  },
  {
    header: '일상점검주기UUID',
    name: 'daily_insp_cycle_uuid',
    width: 200,
    hidden: true,
    format: 'text',
  },
  {
    header: '일상점검주기명',
    name: 'daily_insp_cycle_nm',
    width: 80,
    editable: true,
    format: 'combo',
  },
  {
    header: '주기단위UUID',
    name: 'cycle_unit_uuid',
    width: 200,
    hidden: true,
    format: 'text',
  },
  {
    header: '주기단위',
    name: 'cycle_unit_nm',
    width: 80,
    editable: true,
    format: 'combo',
  },
  {
    header: '점검주기',
    name: 'cycle',
    width: ENUM_WIDTH.M,
    editable: true,
    format: 'number',
    decimal: ENUM_DECIMAL.DEC_NOMAL,
    filter: 'number',
  },
  {
    header: '비고',
    name: 'remark',
    width: ENUM_WIDTH.L,
    editable: true,
    filter: 'text',
  },
] as IGridColumn[];
