export enum MESSAGE {
  PARTNER_TYPE_CREATABLE_NOT_FOUND = '등록할 거래처 유형이 없습니다.',
  PARTNER_TYPE_UPDATABLE_NOT_FOUND = '수정할 거래처 유형이 없습니다.',
  PARTNER_TYPE_DELETABLE_NOT_FOUND = '삭제할 거래처 유형이 없습니다.',
  UNIT_CONVERT_CREATABLE_NOT_FOUND = '등록할 단위 변환 정보가 없습니다.',
  UNIT_CONVERT_UPDATABLE_NOT_FOUND = '수정할 단위 변환 정보가 없습니다.',
  UNIT_CONVERT_DELETABLE_NOT_FOUND = '삭제할 단위 변환 정보가 없습니다.',
  UNIT_CONVERT_CREATE_SUCCESS = '단위 변환 정보가 등록되었습니다.',
  UNIT_CONVERT_UPDATE_SUCCESS = '단위 변환 정보가 수정되었습니다.',
  UNIT_CONVERT_DELETE_SUCCESS = '단위 변환 정보가 삭제되었습니다.',
  UNIT_CONVERT_UUID_IS_REQUIRED = '단위 변환 데이터를 입력해주세요.',
  UNIT_CONVERT_FROM_VALUE_IS_REQUIRED = '변환 전 값은 필수 입력입니다.',
  UNIT_CONVERT_TO_VALUE_IS_REQUIRED = '변환 후 값은 필수 입력입니다.',
  UNIT_CONVERT_CONVER_VALUE_IS_REQUIRED = '변환 값은 필수 입력입니다.',
  UNIT_CONVERT_TO_UNIT_UUID_IS_REQUIRED = '변환 단위는 필수 입력입니다.',
  UNIT_CONVERT_DELETE = '단위 변환 삭제',
  UNIT_CONVERT_DELETE_QUESTION = '단위 변환 정보를 삭제하시겠습니까?',
}
